export const TILE_CONFIG = {
  provider: "maptiler",
  urlTemplate: "https://api.maptiler.com/maps/basic-v2/256/{z}/{x}/{y}.png?key=AoQKjMwQnKa3dQgfKXVC",
  minZoom: 10,
  maxZoom: 16,
  offlineMinZoom: 10,
  offlineMaxZoom: 16,
};

export const appConfig = {
  appName: "Exploracion Field PWA",
  portalUrl: "https://www.arcgis.com",
  apiKey: "",
  defaultMapType: "webmap",
  db: {
    name: "pwa-exploracion-db",
    version: 4,
  },
  storageKeys: {
    activeProjectUuid: "exploracion-active-project-uuid",
    draftCollar: "exploracion-draft-collar",
    captureMode: "exploracion-capture-mode",
    arcgisMapCache: "exploracion-arcgis-map-cache",
    draftHintDismissed: "exploracion-map-draft-hint-dismissed",
  },
  sync: {
    enabled: true,
    provider: "backend",
    autoSyncAfterSave: true,
    autoSyncOnReconnect: true,
    downloadOnStart: false,
    timeoutMs: 12000,
    backend: {
      baseUrl: "https://backend-pwa-production.up.railway.app",
      endpoints: {
        projects: "https://backend-pwa-production.up.railway.app/proyectos",
        collars: "https://backend-pwa-production.up.railway.app/collars",
      },
    },
    arcgis: {
      token: "",
      layers: {
        proyecto: "https://services7.arcgis.com/wkSH3B0op2WjGe48/arcgis/rest/services/EXPLORACION_CAMPO/FeatureServer/3",
        collar: "https://services7.arcgis.com/wkSH3B0op2WjGe48/arcgis/rest/services/EXPLORACION_CAMPO/FeatureServer/0",
        survey: "https://services7.arcgis.com/wkSH3B0op2WjGe48/arcgis/rest/services/EXPLORACION_CAMPO/FeatureServer/4",
        assay: "https://services7.arcgis.com/wkSH3B0op2WjGe48/arcgis/rest/services/EXPLORACION_CAMPO/FeatureServer/1",
        laboratorio: "",
      },
      survey123: {
        laboratorioForm: "https://services7.arcgis.com/wkSH3B0op2WjGe48/arcgis/rest/services/service_1e113afe15e741749db821c9366f65f1_form/FeatureServer/0",
        fields: {
          guiaEnsayo: "GUIA_DE_ENSAYO",
          muestraId: "ID_DE_MUESTRA",
          fechaRecepcion: "FECHA_RECEPCION",
        },
      },
      fields: {
        proyecto: {
          codExploracion: "COD_EXPLORACION",
          concesionArea: "CONCESION_AREA",
          codCatastral: "COD_CATASTRAL",
          localizacion: "LOCALIZACION",
          tecnico: "TECNICO",
          srProyecto: "SR_PROYECTO",
        },
        collar: {
          proyectoGuid: "PROYECTO_GUID",
          holeId: "HOLE_ID",
          este: "ESTE",
          norte: "NORTE",
          elevacion: "ELEVACION",
          profTotal: "PROF_TOTAL",
          tipo: "TIPO",
          localizacion: "LOCALIZACION",
          fecha: "FECHA",
          latitud: "LATITUD",
          longitud: "LONGITUD",
          palabra: "palabra",
        },
        survey: {
          collarGuid: "COLLAR_GUID",
          holeId: "HOLE_ID",
          profundidad: "PROFUNDIDAD",
          dip: "DIP",
          azimut: "AZIMUT",
          instrumento: "INSTRUMENTO",
        },
        assay: {
          collarGuid: "COLLAR_GUID",
          holeId: "HOLE_ID",
          desde: "DESDE",
          hasta: "HASTA",
          material: "MATERIAL",
          descripcion: "DESCRIPCION",
          categoria: "CATEGORIA",
          color: "COLOR",
          grano: "GRANO",
          dureza: "DUREZA",
          humedad: "HUMEDAD",
          presenciaCaolinitica: "PRESENCIA_CAOLINITICA",
          contaminantes: "CONTAMINANTES",
          muestraId: "MUESTRA_ID",
        },
        laboratorio: {
          assayGuid: "ASSAY_GUID",
          muestraId: "MUESTRA_ID",
          fechaRecepcion: "FECHA_RECEPCION",
          laboratorio: "LABORATORIO",
          contraccion: "CONTRACCION",
          absorcion: "ABSORCIÓN",
          colorQ: "COLOR_Q",
          observaciones: "OBSERVACIONES",
        },
      },
    },
  },
  auth: {
    enabled: true,
    provider: "backend-jwt",
    loginUrl: "https://backend-pwa-production.up.railway.app/auth/login",
    refreshUrl: "",
    logoutUrl: "https://backend-pwa-production.up.railway.app/auth/logout",
  },
  map: {
    basemap: "streets-navigation-vector",
    captureTolerance: 12,
    defaultZoom: 15,
    gpsSampleCount: 5,
    gpsTimeoutMs: 18000,
    gpsMaximumAgeMs: 2500,
    offlineExtent: {
      xmin: -81.5,
      ymin: -5.5,
      xmax: -74.5,
      ymax: 1.8,
    },
  },
  elevation: {
    enabled: true,
    deferWhenOffline: true,
    autoResolveOnReconnect: true,
    defaultSourceType: "global",
    globalServiceUrl: "https://elevation3d.arcgis.com/arcgis/rest/services/WorldElevation3D/Terrain3D/ImageServer",
  },
  status: {
    pending: "pendiente",
    synced: "sincronizado",
    error: "error",
    inactive: "inactivo",
  },
  maps: [
    {
      id: "a1e981c32c45489ebadf87f5a910266a",
      type: "webmap",
      title: "MAPA_EXPLORACION",
      description: "Mapa base operativo para captura de collars en campo.",
    },
  ],
};
